# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a3e6f31cd9b912c0c3b753f3ad832b14"
name = "subscription-sync"
handle = "subscription-sync-3"
application_url = "https://forces-doe-infections-prague.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://forces-doe-infections-prague.trycloudflare.com/auth/callback", "https://forces-doe-infections-prague.trycloudflare.com/auth/shopify/callback", "https://forces-doe-infections-prague.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
