# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "188ccf1d41284c331ee1b521244b165b"
name = "subscription-sync"
application_url = "https://subscription-sync-lyart.vercel.app"
embedded = true
handle = "subscription-sync-2"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_inventory,read_locations,read_customers,read_orders,write_orders"

[auth]
redirect_urls = [ "https://subscription-sync-lyart.vercel.app/auth/callback" ]

[pos]
embedded = false
